routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GuestController@index')->name('index');
Route::get('/kids','GuestController@kids')->name('kids');
Route::get('/about', 'GuestController@about')->name('about');
Route::get('/blog', 'GuestController@blog')->name('blog');
Route::get('/boy-single/{slug}', 'GuestController@boy')->name('boy');
Route::get('/boys/{id}', 'GuestController@boys')->name('boys');
Route::post('/checkout', 'CheckoutController@index')->name('checkout');
Route::get('/contact', 'GuestController@contact')->name('contact');
Route::get('/faq', 'GuestController@faq')->name('faq');
Route::get('/girl-single/{slug}', 'GuestController@girl')->name('girl');
Route::get('/girls/{id}', 'GuestController@girls')->name('girls');
Route::get('/men-single/{slug}', 'GuestController@men')->name('men');
Route::get('/mens/{id}', 'GuestController@mens')->name('mens');
Route::get('/payment', 'GuestController@payment')->name('payment');
Route::get('/shop', 'GuestController@shop')->name('shop');
Route::get('/blog-single', 'GuestController@blog_single')->name('blogs.single');
Route::get('/women-single/{slug}', 'GuestController@women')->name('women');
Route::get('/womens/{id}', 'GuestController@womens')->name('womens');
Route::get('/registration', 'GuestController@registration')->name('registration');
Route::get('/u/login', 'GuestController@login')->name('user-login');

Route::get('checkout','CheckoutController@index')->name('checkout.index');

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');
//Route::get('photo', 'PhotoController@index')->name('photo');
//Route::post('photo', 'PhotoController@upload');

//                           UserController

Route::post('/u/login','UserController@login')->name('u.login.check');


//                         AdminUserController

Route::resource('admin-user', 'AdminUserController')->middleware('verified');


//                         AdminRoleController

Route::resource('roles','AdminRoleController')->middleware('verified');

//                       AdminDashboardController

Route::resource('dashboard','AdminDashboardController')->middleware('verified');



//                        AdminProfileController

Route::resource('profile','AdminProfileController')->middleware('verified');


//                       AdminPermissionController

Route::resource('permission','AdminPermissionController')->middleware('verified');

//                        AdminCategoryController

Route::resource('categories','AdminCategoryController')->middleware('verified');
//
//Route::GET('categories','AdminCategoryController@index')->name('categories.index');
//Route::GET('categories/create','AdminCategoryController@create')->name('categories.create');
//Route::POST('categories','AdminCategoryController@store')->name('categories.store');
//Route::GET('categories/{id}','AdminCategoryController@show')->name('categories.show');
//Route::GET('categories/{id}/edit','AdminCategoryController@edit')->name('categories.edit');
//Route::PUT('categories/{id}','AdminCategoryController@update')->name('categories.update');
//Route::DELETE('categories/{id}','AdminCategoryController@destroy')->name('categories.destroy');

//                         AdminBrandController

Route::resource('brands','AdminBrandController')->middleware('verified');

//Route::GET('brands','AdminBrandController@index')->name('brands.index');
//Route::GET('brands/create','AdminBrandController@create')->name('brands.create');
//Route::POST('brands','AdminBrandController@store')->name('brands.store');
//Route::GET('brands/{id}','AdminBrandController@show')->name('brands.show');
//Route::GET('brands/{id}/edit','AdminBrandController@edit')->name('brands.edit');
//Route::PUT('brands/{id}','AdminBrandController@update')->name('brands.update');
//Route::DELETE('brands/{id}','AdminBrandController@destroy')->name('brands.destroy');

Route::resource('products','AdminProductController')->middleware('verified');

//Route::GET('products','AdminProductController@index')->name('products.index');
//Route::GET('products/create','AdminProductController@create')->name('products.create');
//Route::POST('products','AdminProductController@store')->name('products.store');
//Route::GET('products/{id}','AdminProductController@show')->name('products.show');
//Route::GET('products/{id}/edit','AdminProductController@edit')->name('products.edit');
//Route::PUT('products/{id}','AdminProductController@update')->name('products.update');
//Route::DELETE('products/{id}','AdminProductController@destroy')->name('products.destroy');
Route::get('products.publish/{id}','AdminProductController@publish')->name('products.publish');
Route::get('products.unpublish/{id}','AdminProductController@unpublish')->name('products.unpublish');

Route::DELETE('photos/destroy/{photos}','PhotoController@destroy')->name('photos.destroy')->middleware('verified');

resources/views/frontend/blog.blade.php
@extends('layouts.master')
    @section('content')
        <!-- inner banner -->
        <div class="ibanner_w3 pt-sm-5 pt-3">
            <h4 class="head_agileinfo text-center text-capitalize text-center pt-5">
                <span>f</span>ashion
                <span>h</span>ub</h4>
        </div>
        <!-- //inner banner -->
        <!-- breadcrumbs -->
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{route('index')}}">Home</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Blog</li>
            </ol>
        </nav>
        <!-- //breadcrumbs -->
        @include('frontend.partial.feature.blog.blogs')
        <!-- //blog row -->
    @endsection

resources/views/frontend/boy.blade.php
@extends('layouts.master')

@section('content')
	<!-- inner banner -->
	<div class="ibanner_w3 pt-sm-5 pt-3">
		<h4 class="head_agileinfo text-center text-capitalize text-center pt-5">
			<span>f</span>ashion
			<span>h</span>ub</h4>
	</div>
	<!-- //inner banner -->
    <!-- breadcrumbs -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{route('index')}}">Home</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{route('boy')}}">Boy's Clothing</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Single Product</li>
        </ol>
    </nav>
    <!-- //breadcrumbs -->
    <!-- Single -->
    @include('frontend.partial.feature.single')
    <!-- /new_arrivals -->
    @include('frontend.partial.feature.trends')
    <!--// Single -->
@endsection

resources/views/frontend/contact.blade.php
@extends('layouts.master')
@section('head')

@endsection

@section('content')

    <!-- inner banner -->
    <div class="ibanner_w3 pt-sm-5 pt-3">
        <h4 class="head_agileinfo text-center text-capitalize text-center pt-5">
            <span>f</span>ashion
            <span>h</span>ub</h4>
    </div>
    <!-- //inner banner -->
    <!-- breadcrumbs -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="index.html">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Contact Us</li>
        </ol>
    </nav>
    <!-- //breadcrumbs -->
    <!-- contact -->
    @include('frontend.partial.feature.contact')
    <!-- contact -->

@endsection

@section('script')

@endsection

resources/views/frontend/faq.blade.php
@extends('layouts.master')

@section('head')
    <!-- faq -->
    <link href="{{asset('frontend/css/faq.css')}}" rel="stylesheet" type="text/css" media="all" />
@endsection
@section('content')
    <!-- //header -->
	<!-- inner banner -->
	<div class="ibanner_w3 pt-sm-5 pt-3">
		<h4 class="head_agileinfo text-center text-capitalize text-center pt-5">
			<span>f</span>ashion
			<span>h</span>ub</h4>
	</div>
	<!-- //inner banner -->
    <!-- FAQ-help-page -->
    @include('frontend.partial.feature.faq')
    <!-- //FAQ-help-page -->

@endsection

@section('script')
    <!-- script for faq  tabs -->
    <script>
        $(function () {

            var menu_ul = $('.faq > li > ul'),
                menu_a = $('.faq > li > a');

            menu_ul.hide();

            menu_a.click(function (e) {
                e.preventDefault();
                if (!$(this).hasClass('active')) {
                    menu_a.removeClass('active');
                    menu_ul.filter(':visible').slideUp('normal');
                    $(this).addClass('active').next().stop(true, true).slideDown('normal');
                } else {
                    $(this).removeClass('active');
                    $(this).next().stop(true, true).slideUp('normal');
                }
            });

        });
    </script>
    <!-- script for faq tabs -->
@endsection

resources/views/frontend/home.blade.php
@extends('layouts.master')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>Upload Multiple Images</h4>
                    </div>

                    <div class="panel-body">
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                Please correct following errors:
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form action="" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <input type="file" name="image[]" class="form-control-file" multiple="true">
                            </div>

                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>

                        <hr>
                        <h3>Listing Images</h3>

                        @forelse($photos as $photo)
                            <div class="col-md-4">
                                <img src="{{ $photo->thumbnail }}" class="img-responsive">
                            </div>
                        @empty
                            No image found
                        @endforelse
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/frontend/index.blade.php
@extends('layouts.master')

@section('content')
    <!-- banner -->
    @include('frontend.partial.feature.banner')
    <!-- //banner -->
    <!--services-->
    @include('frontend.partial.feature.service')
    <!-- //services-->
    <!-- about -->
    @include('frontend.partial.feature.about')
    <!-- //about -->
    <!-- product tabs -->
    @include('frontend.partial.feature.products')
    <!-- //product tabs -->
    <!-- insta posts -->
    @include('frontend.partial.feature.insta')
    <!-- //insta posts -->
@endsection
<!-- footer -->
<!-- //footer -->
<!-- sign up Modal -->
@section('modal')
    @include('frontend.partial.construct.modal')
@endsection
<!-- signin Modal -->
<!-- js -->

resources/views/frontend/men.blade.php
@extends('layouts.master')

@section('content')
	<!-- inner banner -->
	<div class="ibanner_w3 pt-sm-5 pt-3">
		<h4 class="head_agileinfo text-center text-capitalize text-center pt-5">
			<span>f</span>ashion
			<span>h</span>ub</h4>
	</div>
	<!-- //inner banner -->
	<!-- breadcrumbs -->
	<nav aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a href="index.html">Home</a>
			</li>
			<li class="breadcrumb-item">
				<a href="men.blade.php">Men's Clothing</a>
			</li>
			<li class="breadcrumb-item active" aria-current="page">Single Product</li>
		</ol>
	</nav>
	<!-- //breadcrumbs -->
	<!-- Single -->
	@include('frontend.partial.feature.single')
	<!-- /new_arrivals -->
	@include('frontend.partial.feature.trends')
	<!--// Single -->
@endsection

resources/views/frontend/mens.blade.php
@extends('layouts.master')

@section('head')

@endsection
@section('content')
    <!-- //header container -->
    <!-- inner banner -->
    <div class="ibanner_w3 pt-5">
        <h4 class="head_agileinfo text-center text-capitalize text-center pt-5">
            <span>f</span>ashion
            <span>h</span>ub</h4>
    </div>
    <!-- //inner banner -->
    <!-- breadcrumbs -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{route('index')}}">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Men's Clothing</li>
        </ol>
    </nav>
    <!-- //breadcrumbs -->
    <!-- Shop -->
    @include('frontend.partial.feature')
    <!--// Shop -->
@endsection

@section('script')
    <!-- price range (top products) -->
    <script src="{{asset('frontend/js/jquery-ui.js')}}"></script>
    <script>
        //<![CDATA[
        $(window).load(function () {
            $("#slider-range").slider({
                range: true,
                min: 0,
                max: 9000,
                values: [50, 6000],
                slide: function (event, ui) {
                    $("#amount").val("$" + ui.values[0] + " - $" + ui.values[1]);
                }
            });
            $("#amount").val("$" + $("#slider-range").slider("values", 0) + " - $" + $("#slider-range")
                .slider(
                    "values", 1));

        }); //]]>
    </script>
    <!-- //price range (top products) -->
@endsection

resources/views/frontend/payment.blade.php
@extends('layouts.master')

@section('head')
    <link href="{{asset('frontend/css/checkout.css')}}" type="text/css" rel="stylesheet" media="all">
    <!-- easy-responsive-tabs css -->
    <link rel="stylesheet" href="{{asset('frontend/css/easy-responsive-tabs.css')}}" type="text/css" media="all" />
@endsection


@section('content')<!-- inner banner -->
	<div class="ibanner_w3 pt-sm-5 pt-3">
		<h4 class="head_agileinfo text-center text-capitalize text-center pt-5">
			<span>f</span>ashion
			<span>h</span>ub</h4>
	</div>
	<!-- //inner banner -->
    <!-- breadcrumbs -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="index.html">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Payment</li>
        </ol>
    </nav>
    <!-- //breadcrumbs -->
    <!--Payment-->
    @include('frontend.partial.feature.payment')
    <!-- //payment -->
@endsection

@section('script')
    <!-- easy-responsive-tabs -->
    <script src="{{asset('frontend/js/easy-responsive-tabs.js')}}"></script>
    <script>
        $(document).ready(function () {
            $('#horizontalTab').easyResponsiveTabs({
                type: 'default', //Types: default, vertical, accordion
                width: 'auto', //auto or any width like 600px
                fit: true, // 100% fit in a container
                closed: 'accordion', // Start closed if in accordion view
                activate: function (event) { // Callback function if tab is switched
                    var $tab = $(this);
                    var $info = $('#tabInfo');
                    var $name = $('span', $info);
                    $name.text($tab.text());
                    $info.show();
                }
            });
        });
    </script>
    <!-- //easy-responsive-tabs -->

    <!-- credit-card -->
    <script src="{{asset('frontend/js/creditly.js')}}"></script>
    <link rel="stylesheet" href="{{asset('frontend/css/creditly.css')}}" type="text/css" media="all" />

    <script>
        $(function () {
            var creditly = Creditly.initialize(
                '.creditly-wrapper .expiration-month-and-year',
                '.creditly-wrapper .credit-card-number',
                '.creditly-wrapper .security-code',
                '.creditly-wrapper .card-type');

            $(".creditly-card-form .submit").click(function (e) {
                e.preventDefault();
                var output = creditly.validate();
                if (output) {
                    // Your validated credit card output
                    console.log(output);
                }
            });
        });
    </script>
    <!-- //credit-card -->
@endsection

resources/views/frontend/register.blade.php
@extends('layouts.master')

@section('content')
<!-- sign up Modal -->
<div class="modal fade" id="myModal_btn" tabindex="-1" role="dialog" aria-labelledby="myModal_btn" aria-hidden="true">
    <div class="agilemodal-dialog modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Register Now</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body pt-3 pb-5 px-sm-5">
                <div class="row">
                    <div class="col-md-6 mx-auto align-self-center">
                        <img src="{{asset('frontend/images/p3.png')}}" class="img-fluid" alt="login_image" />
                    </div>
                    <div class="col-md-6">
                        <form action="{{route('user.store')}}" method="POST">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            @CSRF
                            <div class="form-group">
                                <label for="recipient-name1" class="col-form-label">Your Name</label>
                                <input type="text" class="form-control {{ $errors->has('first_name') ? ' is-invalid' : '' }}" placeholder=" " name="first_name" id="recipient-name1" value="{{old('first_name')}}"  required>
                            </div>
                            <div class="form-group">
                                <label for="recipient-name1" class="col-form-label">User Name</label>
                                <input type="text" class="form-control {{ $errors->has('username') ? ' is-invalid' : '' }}" placeholder=" " name="username" id="recipient-name1" value="{{old('username')}}"  required>
                            </div>
                            <div class="form-group">
                                <label for="recipient-email" class="col-form-label">Email</label>
                                <input type="email" class="form-control {{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{old('email')}}"id="recipient-email"  required autofocus >
                            </div>
                            <div class="form-group">
                                <label for="password1" class="col-form-label">Password</label>
                                <input type="password" class="form-control {{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" id="password1" required>
                            </div>
                            <div class="form-group">
                                <label for="password2" class="col-form-label">Confirm Password</label>
                                <input type="password" class="form-control" placeholder=" " name="password_confirmation" id="password2" required>
                            </div>
                            <div class="sub-w3l">
                                <div class="sub-agile">
                                    <input type="checkbox" id="brand2" value="">
                                    <label for="brand2" class="mb-3">
                                        <span></span>I Accept to the Terms & Conditions</label>
                                </div>
                            </div>
                            <div class="right-w3l">
                                <input type="submit" class="form-control" value="Register">
                            </div>
                        </form>
                        <p class="text-center mt-3">Already a member?
                            <a href="#" data-toggle="modal" data-target="#exampleModal1" class="text-dark login_btn">
                                Login Now</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- //signup modal -->
@endsection

resources/views/frontend/shop.blade.php
@extends('layouts.master')

@section('head')

@endsection
@section('content')
    <!-- //header container -->
    <!-- inner banner -->
    <div class="ibanner_w3 pt-5">
        <h4 class="head_agileinfo text-center text-capitalize text-center pt-5">
            <span>f</span>ashion
            <span>h</span>ub</h4>
    </div>
    <!-- //inner banner -->
    <!-- breadcrumbs -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="index.html">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Shop</li>
        </ol>
    </nav>
    <!-- //breadcrumbs -->
    <!-- Shop -->
    @include('frontend.partial.feature.shop.shop')
    <!--// Shop -->
@endsection

@section('script')
    <!-- price range (top products) -->
    <script src="js/jquery-ui.js"></script>
    <script>
        //<![CDATA[
        $(window).load(function () {
            $("#slider-range").slider({
                range: true,
                min: 0,
                max: 9000,
                values: [50, 6000],
                slide: function (event, ui) {
                    $("#amount").val("$" + ui.values[0] + " - $" + ui.values[1]);
                }
            });
            $("#amount").val("$" + $("#slider-range").slider("values", 0) + " - $" + $("#slider-range").slider(
                "values", 1));

        }); //]]>
    </script>
    <!-- //price range (top products) -->
@endsection

resources/views/frontend/single.blade.php
@extends('layouts.master')

@section('content')
	<!-- inner banner -->
	<div class="ibanner_w3 pt-sm-5 pt-3">
		<h4 class="head_agileinfo text-center text-capitalize text-center pt-5">
			<span>f</span>ashion
			<span>h</span>ub</h4>
	</div>
	<!-- //inner banner -->
    <!-- breadcrumbs -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="index.html">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Single Page</li>
        </ol>
    </nav>
    <!-- //breadcrumbs -->
    @include('partial.feature.blog.single-blog')
    <!-- //blog-->

@endsection

resources/views/frontend/women.blade.php
@extends('layouts.master')

@section('content')
	<!-- inner banner -->
	<div class="ibanner_w3 pt-sm-5 pt-3">
		<h4 class="head_agileinfo text-center text-capitalize text-center pt-5">
			<span>f</span>ashion
			<span>h</span>ub</h4>
	</div>
	<!-- //inner banner -->
	<!-- breadcrumbs -->
	<nav aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a href="index.html">Home</a>
			</li>
			<li class="breadcrumb-item active" aria-current="page">Women's Clothing</li>
		</ol>
	</nav>
	<!-- //breadcrumbs -->
	<!-- Single -->
	@include('frontend.partial.feature.single')
	<!-- /new_arrivals -->
	@include('frontend.partial.feature.trends')
	<!--// Single -->
@endsection