routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GuestController@index')->name('index');
Route::get('/kids','GuestController@kids')->name('kids');
Route::get('/about', 'GuestController@about')->name('about');
Route::get('/blog', 'GuestController@blog')->name('blog');
Route::get('/boy-single/{slug}', 'GuestController@boy')->name('boy');
Route::get('/boys/{id}', 'GuestController@boys')->name('boys');
Route::post('/checkout', 'CheckoutController@index')->name('checkout');
Route::get('/contact', 'GuestController@contact')->name('contact');
Route::get('/faq', 'GuestController@faq')->name('faq');
Route::get('/girl-single/{slug}', 'GuestController@girl')->name('girl');
Route::get('/girls/{id}', 'GuestController@girls')->name('girls');
Route::get('/men-single/{slug}', 'GuestController@men')->name('men');
Route::get('/mens/{id}', 'GuestController@mens')->name('mens');
Route::get('/payment', 'GuestController@payment')->name('payment');
Route::get('/shop', 'GuestController@shop')->name('shop');
Route::get('/blog-single', 'GuestController@blog_single')->name('blogs.single');
Route::get('/women-single/{slug}', 'GuestController@women')->name('women');
Route::get('/womens/{id}', 'GuestController@womens')->name('womens');
Route::get('/registration', 'GuestController@registration')->name('registration');
Route::get('/u/login', 'GuestController@login')->name('user-login');

Route::get('checkout','CheckoutController@index')->name('checkout.index');

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');
//Route::get('photo', 'PhotoController@index')->name('photo');
//Route::post('photo', 'PhotoController@upload');

//                           UserController

Route::post('/u/login','UserController@login')->name('u.login.check');


//                         AdminUserController

Route::resource('admin-user', 'AdminUserController')->middleware('verified');


//                         AdminRoleController

Route::resource('roles','AdminRoleController')->middleware('verified');

//                       AdminDashboardController

Route::resource('dashboard','AdminDashboardController')->middleware('verified');



//                        AdminProfileController

Route::resource('profile','AdminProfileController')->middleware('verified');


//                       AdminPermissionController

Route::resource('permission','AdminPermissionController')->middleware('verified');

//                        AdminCategoryController

Route::resource('categories','AdminCategoryController')->middleware('verified');
//
//Route::GET('categories','AdminCategoryController@index')->name('categories.index');
//Route::GET('categories/create','AdminCategoryController@create')->name('categories.create');
//Route::POST('categories','AdminCategoryController@store')->name('categories.store');
//Route::GET('categories/{id}','AdminCategoryController@show')->name('categories.show');
//Route::GET('categories/{id}/edit','AdminCategoryController@edit')->name('categories.edit');
//Route::PUT('categories/{id}','AdminCategoryController@update')->name('categories.update');
//Route::DELETE('categories/{id}','AdminCategoryController@destroy')->name('categories.destroy');

//                         AdminBrandController

Route::resource('brands','AdminBrandController')->middleware('verified');

//Route::GET('brands','AdminBrandController@index')->name('brands.index');
//Route::GET('brands/create','AdminBrandController@create')->name('brands.create');
//Route::POST('brands','AdminBrandController@store')->name('brands.store');
//Route::GET('brands/{id}','AdminBrandController@show')->name('brands.show');
//Route::GET('brands/{id}/edit','AdminBrandController@edit')->name('brands.edit');
//Route::PUT('brands/{id}','AdminBrandController@update')->name('brands.update');
//Route::DELETE('brands/{id}','AdminBrandController@destroy')->name('brands.destroy');

Route::resource('products','AdminProductController')->middleware('verified');

//Route::GET('products','AdminProductController@index')->name('products.index');
//Route::GET('products/create','AdminProductController@create')->name('products.create');
//Route::POST('products','AdminProductController@store')->name('products.store');
//Route::GET('products/{id}','AdminProductController@show')->name('products.show');
//Route::GET('products/{id}/edit','AdminProductController@edit')->name('products.edit');
//Route::PUT('products/{id}','AdminProductController@update')->name('products.update');
//Route::DELETE('products/{id}','AdminProductController@destroy')->name('products.destroy');
Route::get('products.publish/{id}','AdminProductController@publish')->name('products.publish');
Route::get('products.unpublish/{id}','AdminProductController@unpublish')->name('products.unpublish');

Route::DELETE('photos/destroy/{photos}','PhotoController@destroy')->name('photos.destroy')->middleware('verified');

app/Permission.php
<?php

namespace App;

use Zizaco\Entrust\EntrustPermission;

class Permission extends EntrustPermission
{
}

resources/views/admin/permission/create.blade.php
@extends('layouts.admin')
@section('navbar')
    <a class="navbar-brand" href="#">Role Created by Authority</a>
@endsection
@section('content')

    <div class="wrapper ">

        @include('admin.partial.sidebar')

        <div class="main-panel">
            <!-- Navbar -->
        @include('admin.partial.nav')


        <!--  User Details -->
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="card">
                                <div class="card-header card-header-primary">
                                    <h4 class="card-title">Create Role</h4>
                                    <p class="card-category">Authority can Create Role Here...</p>
                                </div>
                                <div class="card-body" >
                                    <form action="{{route('permission.store')}}" method="POST">
                                        @CSRF
                                        <div class="row">
                                            <div class="col-md-1"></div>
                                            <div class="col-md-10">
                                                @if ($errors->any())
                                                    <div class="alert alert-danger">
                                                        <ul>
                                                            @foreach ($errors->all() as $error)
                                                                <li>{{ $error }}</li>
                                                            @endforeach
                                                        </ul>
                                                    </div>
                                                @endif
                                            </div>
                                            <span><br/></span></div>
                                        <div class="row">
                                            <div class="col-md-2"></div>
                                            <div class="col-md-8">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating">Permission Name</label>
                                                    <input type="text" class="form-control" name="name">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-2"></div>
                                            <div class="col-md-8">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating">Display Name</label>
                                                    <input type="text" class="form-control" name="display_name">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-2"></div>
                                            <div class="col-md-8">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating">Description</label>
                                                    <input type="text" class="form-control" name="description">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-3"></div>
                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <button type="submit" class="btn btn-primary pull-right">Create Permission</button>
                                                </div>
                                            </div>
                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <button class="btn btn-primary pull-right" type="reset" ><a href="{{route('admin-user.index')}}" >Cancel</a></button>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <!-- Footer -->
            @include('admin.partial.footer')
        </div>
    </div>

    {{--@include('admin.partial.plugin')--}}

    @include('admin.partial.script')
@endsection

@section('script')
    <script>
        const x = new Date().getFullYear();
        let date = document.getElementById('date');
        date.innerHTML = '&copy; ' + x + date.innerHTML;

        function checkPermission() {
            let checkBox = document.getElementById("checkBox");
            let permissionBox = document.getElementById("permissionBox");
            if (checkBox.checked !== true){
                permissionBox.style.display = "block";
            } else {
                permissionBox.style.display = "none";
            }
        }

        function toggle(source) {
            let checkboxes = document.querySelectorAll('input[type="checkbox"]');
            for (let i = 0; i < checkboxes.length; i++) {
                if (checkboxes[i] !== source)
                    checkboxes[i].checked = source.checked;
            }
        }
    </script>



@endsection

resources/views/admin/permission/index.blade.php
@extends('layouts.admin')

@section('head')

@endsection

@section('navbar')
    <a class="navbar-brand" href="#" title="View Customer Users table">All Permission Table</a>
@endsection

@section('content')

    <div class="wrapper ">

        @include('admin.partial.sidebar')


        <div class="main-panel">
            <!-- Navbar -->
            @include('admin.partial.nav')
            <!-- End Navbar -->

            <!-- User List Table  -->

            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12" id="admin" style="display: block;">
                            <div class="card">
                                <div class="card-header card-header-success">
                                    @if(session('message'))
                                        <h3 style="text-align: center; color:snow; font-weight: bold;" class="card-title">{{session('message')}}</h3>
                                    @endif
                                </div>
                                <div class="card-header card-header-primary">
                                    <div class="col-md-4 "style="float:left;">
                                        <h4 class="card-title ">Authorized User Role</h4>
                                        <p class="card-category">Authorized Users Role Table</p>
                                    </div>
                                    <div class="col-md-4" style="float:left;">
                                        <h4 class="card-title"><a  class="nav-link navbar-brand" href="{{route('permission.create')}}"  title="Create New Role">Create New Permission</a></h4>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <table class="table" id="table_id">
                                            <thead class=" text-primary">
                                            <th>
                                                ID No
                                            </th>
                                            <th>
                                                Display Name
                                            </th>
                                            <th>
                                                Permission
                                            </th>
                                            <th style="max-width:300px;">
                                                Description
                                            </th>
                                            <th class="action-btn">
                                                Action
                                            </th>
                                            </thead>
                                            <tbody>
                                            @foreach($permissions as $permission)
                                                <tr style="background:#202940;">
                                                    <td>
                                                        {{ $permission->id }}
                                                    </td>
                                                    <td>
                                                        {{ $permission->display_name }}
                                                    </td>
                                                    <td>
                                                        <span class="label success">{{ $permission->name }}</span>
                                                    </td>
                                                    <td>
                                                        {!! $permission->description !!}
                                                    </td>
                                                    <td class="center">
                                                        <a class="m-btn btn btn-success" href="{{route('permission.show',$permission->id)}}">
                                                            <i class="material-icons">search</i>
                                                        </a>
                                                        <a class="m-btn btn btn-info" href="{{route('permission.edit',$permission->id)}}">
                                                            <i class="material-icons">settings</i>
                                                        </a>
                                                        <form style="display: inline !important;" action="{{route('permission.destroy', $permission->id)}}" method="POST">
                                                            @CSRF
                                                            @METHOD('DELETE')
                                                            <button type="submit" class="m-btn btn btn-danger" title="Delete User" onclick="return confirmDelete()">
                                                                <i class="material-icons">delete</i>
                                                            </button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


            <!--  Footer  -->

            @include('admin.partial.footer')

        </div>
    </div>

    @include('admin.partial.script')
@endsection

@section('script')

    <script>
        const x = new Date().getFullYear();
        let date = document.getElementById('date');
        date.innerHTML = '&copy; ' + x + date.innerHTML;
    </script>

    <script>
        function toggle_visibility(id1,id2,id3,id4) {
            let a = document.getElementById(id1);
            let u = document.getElementById(id2);
            let ab = document.getElementById(id3);
            let ub = document.getElementById(id4);
            a.style.display = ((a.style.display!=='none') ? 'none' : 'block');
            u.style.display = ((u.style.display!=='none') ? 'none' : 'block');
            ab.style.display = ((ab.style.display!=='none') ? 'none' : 'block');
            ub.style.display = ((ub.style.display!=='none') ? 'none' : 'block');
        }

        function confirmDelete() {
            let del = confirm('Are you sure to delete this Role?');
            if(del)
                return true;
            else
                return false;
        }

    </script>

@endsection

resources/views/admin/permission/show.blade.php
@extends('layouts.admin')

@section('head')

@endsection

@section('navbar')
    <!-- <a class="navbar-brand" id="user-b" style="display: block;" href="#" onclick="toggle_visibility('admin', 'user','user-b','admin-b');" title="View Authenticate Users table">View Authenticate Users</a>
    <a class="navbar-brand" id="admin-b" style="display: none;" href="#" onclick="toggle_visibility('admin','user','user-b','admin-b');" title="View Customer Users table">View Customer Users</a> -->
@endsection

@section('content')

    <div class="wrapper ">

        @include('admin.partial.sidebar')


        <div class="main-panel">
            <!-- Navbar -->
        @include('admin.partial.nav')
        <!-- End Navbar -->

            <!-- User List Table  -->

            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header card-header-primary">
                                    <div class="col-md-4 "style="float:left;">
                                        <h4 class="card-title ">Permission</h4>
                                        <p class="card-category">Permissions Table</p>
                                    </div>
                                    <div class="col-md-4" style="float:left;">
                                        <h4 class="card-title"><a  class="nav-link navbar-brand" href="{{route('permission.create')}}"  title="Create New Role">Create New Permission</a></h4>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <table class="table">
                                            <thead class=" text-primary">
                                            <th>
                                                ID No
                                            </th>
                                            <th>
                                                Display Name
                                            </th>
                                            <th>
                                                Permission Name
                                            </th>
                                            <th>
                                                Description
                                            </th>
                                            <th class="action-btn">
                                                Action
                                            </th>
                                            </thead>
                                            <tbody>
                                            <tr style="background:#202940;">
                                                <td>
                                                    {{ $permissions->id }}
                                                </td>
                                                <td>
                                                    {{ $permissions->display_name }}
                                                </td>
                                                <td>
                                                    <span class="label success">{{ $permissions->name }}</span>
                                                </td>
                                                <td>
                                                    {!! $permissions->description !!}
                                                </td>
                                                <td class="center">
                                                    <a class="m-btn btn btn-success" href="{{route('permission.show',$permissions->id)}}">
                                                        <i class="material-icons">search</i>
                                                    </a>
                                                    <a class="m-btn btn btn-info" href="{{route('permission.edit',$permissions->id)}}">
                                                        <i class="material-icons">settings</i>
                                                    </a>
                                                    <form style="display: inline !important;" action="{{route('permission.destroy', $permissions->id)}}" method="POST">
                                                        @CSRF
                                                        @METHOD('PUT')
                                                        <button type="submit" class="m-btn btn btn-danger" title="Delete User" onclick="return confirmDelete()">
                                                            <i class="material-icons">delete</i>
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <!--  Footer  -->

        @include('admin.partial.footer')

    </div>
    </div>

@endsection

@section('script')

    <script>
        const x = new Date().getFullYear();
        let date = document.getElementById('date');
        date.innerHTML = '&copy; ' + x + date.innerHTML;
    </script>

    <script>
        function toggle_visibility(id1,id2,id3,id4) {
            let a = document.getElementById(id1);
            let u = document.getElementById(id2);
            let ab = document.getElementById(id3);
            let ub = document.getElementById(id4);
            a.style.display = ((a.style.display!=='none') ? 'none' : 'block');
            u.style.display = ((u.style.display!=='none') ? 'none' : 'block');
            ab.style.display = ((ab.style.display!=='none') ? 'none' : 'block');
            ub.style.display = ((ub.style.display!=='none') ? 'none' : 'block');
        }

        function confirmDelete(){
            let del = confirm('Are You Sure to Delete this Role?');
            if(del)
                return true;
            else
                return false;
        }
    </script>

@endsection